spring.datasource:
  url: jdbc:postgresql://localhost:5438/postgres
  username: postgres
  password: postgres

flyway.clean-on-validation-error: true

ro.msg.poc:
  bucket: s3vsrdsimagesstack-storagebucket5cb7c8ea-12ctb3vpdf9m1
  distDomain: d3868m77tv82em.cloudfront.net
  keyId: K2916OSBBSS1KW