/*
 * This file is generated by jOOQ.
 */
package ro.msg.poc.images.db;


import ro.msg.poc.images.db.tables.Image;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.image</code>.
     */
    public static final Image IMAGE = Image.IMAGE;
}
